### ISSUE TITLE
Wrong formula

### ISSUE THREAD

**Issue by jknodlseder** [BrunoArsioli/TS-DegFreedom-Sigma-relation-FermiLAT#1]
Your formula needs to be changed, it has to read

`sigma = norm.isf(distributions.chi2.sf(ts,dof)/2.0)`

hence you need to divide the Chi2 by 2.

You can test this for `dof=1`for which the sigma is the square root of TS.

**Comment by BrunoArsioli** [comment]
Thank you for point it out!
